AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  query-ap
  Sample SAM Template for query-api


Resources:
  AuthorizationLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AuthorizationLayer
      ContentUri: py-jose.zip
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7


Outputs:
  AuthorizationLayer:
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'AuthorizationLayer' ] ]
    Value: !Ref AuthorizationLayer